#!/bin/bash

set -e

HDMI_STATUS=$(</sys/class/drm/card0/card0-HDMI-A-1/status)

touch ~/hotpluglog
echo $HDMI_STATUS >> ~/hotpluglog

if [ "connected" == "$HDMI_STATUS" ]; then  
    /usr/bin/xrandr --output HDMI1 --left-of eDP1 --auto
    # /usr/bin/notify-send --urgency=low -t 5000 "HDMI Connected"
else  
    /usr/bin/xrandr --output HDMI1 --off
    # /usr/bin/notify-send --urgency=low -t 5000 "HDMI Disconnected"
    # exit
fi
