#!/bin/bash

round() {
    echo $(( ${1:?need one argument} / 2 * 2))
}

readonly VIDEOSHOTDIR="$HOME/.cache/videoshot"

if [[ ! -e $VIDEOSHOTDIR ]]; then
    mkdir -p "$VIDEOSHOTDIR"
fi

readonly PIDPATH="$VIDEOSHOTDIR/videoshot.pid"
readonly RESOURCEPATH="$VIDEOSHOTDIR/videoshot.txt"

if [[ ! -f "$PIDPATH" ]]; then
    readonly border="-show_region 1"
    readonly rect_encopts="-r 30 -c:v libx264 -preset slow -crf 18 -c:a libvorbis"
    readonly ffmpeg_display=$DISPLAY
    read -r X Y W H G ID < <(slop -f "%x %y %w %h %g %i")
    readonly X=$(round $X)
    readonly Y=$(round $Y)
    readonly W=$(round $W)
    readonly H=$(round $H)
    readonly TIME="$(date +%Y-%m-%d-%H-%M-%S)"
    readonly VIDPATH="$VIDEOSHOTDIR/rec-$TIME.mp4"
    (
    ffmpeg -f x11grab ${border} -s "$W"x"$H" -i $ffmpeg_display+$X,$Y $rect_encopts "$VIDPATH" &
    echo "$!" > "$PIDPATH"
    echo "$VIDPATH" > "$RESOURCEPATH"
    notify-send "Start recording" "$VIDPATH"
    readonly PID="$(cat $PIDPATH)"
    wait "$PID"
    readonly VIDPATH="$(cat $RESOURCEPATH)"
    readonly OUTPUT="$(fb "$VIDPATH")"
    notify-send "Video uploaded" "$OUTPUT"
    rm "$PIDPATH"
    rm "$RESOURCEPATH"
    ) &
else
    readonly PID="$(cat $PIDPATH)"
    kill "$PID"
fi
